#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================
server:
  port: 5443
# ==============================================================
# = Impostazioni ssl
# ==============================================================
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certificato.p12
    key-store-password: 123_Stella

spring:
  logging:
    level:
      org.springframework: DEBUG
  messages:
    basename: messages
  application:
    name: ArticoliWebService
  #==========================================================
  #= PARAMETRI DBMS POSTGRESQL
  #==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Adiener
    url: jdbc:postgresql://localhost:5433/shop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#==========================================================
#Opzioni di Accesso Servizio gestuser
#==========================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: 123Stella

#==========================================================
# - Parametri Sicurezza JWT
#==========================================================
sicurezza:
  header: Authorization
  secret: $123_Stella@adiener.it$

#==========================================================
# - Livello Log di Sicurezza
#==========================================================
logging:
  level:
    org.springframework.security: DEBUG

