#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================

# Configurazione del server
server:
  port: 5443
  # Configurazione SSL
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certificato.p12
    key-store-password: 123_Stella

# Configurazione Spring
spring:
  # Configurazione logging
  logging:
    level:
      org.springframework: DEBUG
  # Configurazione messaggi
  messages:
    basename: messages
  # Nome dell'applicazione
  application:
    name: ArticoliWebService

  #==========================================================
  #= PARAMETRI DBMS POSTGRESQL
  #==========================================================
  # Inizializzazione SQL
  sql:
    init:
      mode: always
      platform: postgres
  # Configurazione del datasource
  datasource:
    password: 123_Adiener
    url: jdbc:postgresql://localhost:5433/shop
    username: postgres
  # Configurazione JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#==========================================================
# Opzioni di Accesso Servizio gestuser
#==========================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: 123Stella

#==========================================================
# - Parametri Sicurezza JWT
#==========================================================
sicurezza:
  header: Authorization
  secret: $123_Stella@adiener.it$

#==========================================================
# - Livello Log di Sicurezza
#==========================================================
logging:
  level:
    org.springframework.security: DEBUG