#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================

# Configurazione del server
server:
  port: 5443
  # Configurazione SSL
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certificato.p12
    key-store-password: 123_Stella

# Configurazione Spring
spring:
  # Configurazione messaggi
  messages:
    basename: messages
  # Nome dell'applicazione
  application:
    name: ArticoliWebService

  #==========================================================
  #= PARAMETRI DBMS POSTGRESQL
  #==========================================================
  # Inizializzazione SQL
  sql:
    init:
      mode: always
      platform: postgres
  # Configurazione del datasource
  datasource:
    password: 123_Adiener
    url: jdbc:postgresql://localhost:5433/shop
    username: postgres
  # Configurazione JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


#==========================================================
#= Parametri Attuatore
#==========================================================
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED

#==========================================================
# = Proprietà Livello Log
# = Default ERROR, WARN, INFO
# = Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
#==========================================================
logging:
  file:
    name: './logs/ArtSrv.log'
    max-size: 1MB
    #path: /logs
  pattern:
    file: "%d{dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n"
    #console: "%d{dd-MM-yyyy HH:mm:s} - %msg%n"
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate: INFO
    org.springframework.web: INFO
    com.xantrix.webapp.controllers: INFO

#==========================================================
# Opzioni di Accesso Servizio gestuser
#==========================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: 123Stella

#==========================================================
# - Parametri Sicurezza JWT
#==========================================================
sicurezza:
  header: Authorization
  secret: $123_Stella@adiener.it$